version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pda-laravel
    container_name: pda-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - pda-laravel

  nginx:
    image: nginx:alpine
    container_name: pda-laravel-nginx
    restart: unless-stopped
    ports:
      - "7777:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pda-laravel

  db:
    image: mysql:8.0
    container_name: pda-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pda
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pda-laravel

networks:
  pda-laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local